import hashlib
import tempfile
import unittest
import zipfile
from dataclasses import replace
from pathlib import Path

from cue import retarget_cue
from iso2xa import convert_iso_to_bin
from psxfoundry.disc import (
    DiscAnalysisError,
    analyze_disc,
    group_disc_sets,
)


SECTOR_SIZE = 2352


def disc_bytes(sectors, serial=b"SCES_028.34"):
    data = bytearray(sectors * SECTOR_SIZE)
    data[512 : 512 + len(serial)] = serial
    return bytes(data)


def iso_record(name, extent, size, *, directory=False):
    encoded = name if isinstance(name, bytes) else name.encode("ascii")
    length = 33 + len(encoded) + (len(encoded) % 2 == 0)
    record = bytearray(length)
    record[0] = length
    record[2:6] = extent.to_bytes(4, "little")
    record[6:10] = extent.to_bytes(4, "big")
    record[10:14] = size.to_bytes(4, "little")
    record[14:18] = size.to_bytes(4, "big")
    record[25] = 2 if directory else 0
    record[28:30] = (1).to_bytes(2, "little")
    record[30:32] = (1).to_bytes(2, "big")
    record[32] = len(encoded)
    record[33 : 33 + len(encoded)] = encoded
    return bytes(record)


def playstation_iso(boot):
    image = bytearray(32 * 2048)
    root_record = iso_record(b"\x00", 20, 2048, directory=True)
    descriptor = memoryview(image)[16 * 2048 : 17 * 2048]
    descriptor[0:7] = b"\x01CD001\x01"
    descriptor[156 : 156 + len(root_record)] = root_record
    image[17 * 2048 : 17 * 2048 + 7] = b"\xffCD001\x01"

    system = b"BOOT = cdrom:\\SCES_028.34;1\r\n"
    records = b"".join(
        (
            iso_record(b"\x00", 20, 2048, directory=True),
            iso_record(b"\x01", 20, 2048, directory=True),
            iso_record("SYSTEM.CNF;1", 21, len(system)),
            iso_record("SCES_028.34;1", 22, len(boot)),
        )
    )
    image[20 * 2048 : 20 * 2048 + len(records)] = records
    image[21 * 2048 : 21 * 2048 + len(system)] = system
    image[22 * 2048 : 22 * 2048 + len(boot)] = boot
    return bytes(image)


class DiscAnalysisTests(unittest.TestCase):
    def test_boot_fingerprint_is_independent_of_disc_container(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            boot = b"PS-X EXE" + bytes(2040) + b"patched selector"
            cooked = root / "Game.iso"
            cooked.write_bytes(playstation_iso(boot))
            raw = root / "Game.bin"
            convert_iso_to_bin(cooked, raw)
            cue = root / "Game.cue"
            cue.write_text(
                'FILE "Game.bin" BINARY\n'
                "  TRACK 01 MODE2/2352\n"
                "    INDEX 01 00:00:00\n",
                encoding="utf-8",
            )

            descriptions = tuple(analyze_disc(path) for path in (cooked, raw, cue))

            self.assertEqual({disc.disc_id for disc in descriptions}, {"SCES02834"})
            self.assertEqual({disc.boot_path for disc in descriptions}, {"SCES_028.34"})
            self.assertEqual(
                {disc.boot_sha256 for disc in descriptions},
                {hashlib.sha256(boot).hexdigest()},
            )
            self.assertEqual(descriptions[0].tracks[0].mode, "MODE2/2048")
            self.assertEqual(descriptions[1].tracks[0].mode, "MODE2/2352")
            self.assertNotEqual(descriptions[0].sha256, descriptions[1].sha256)
            self.assertIn("no raw sectors", descriptions[0].warnings[0])

    def test_retargets_generated_cue_to_its_local_image(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            image = root / "Game.bin"
            image.write_bytes(disc_bytes(2))
            cue = root / "Game.cue"
            cue.write_text(
                "REM generated by chdman\n"
                'FILE "/private/tmp/extracted.bin" BINARY\n'
                "  TRACK 01 MODE2/2352\n"
                "    INDEX 01 00:00:00\n",
                encoding="utf-8",
            )

            retarget_cue(cue, cue, image.name)

            result = analyze_disc(cue)
            self.assertEqual(result.disc_id, "SCES02834")
            self.assertIn('FILE "Game.bin" BINARY', cue.read_text(encoding="utf-8"))

    def test_analyzes_mixed_mode_cue_without_changing_source(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            image = root / "GAME.BIN"
            source = disc_bytes(6)
            image.write_bytes(source)
            cue = root / "Game.cue"
            cue.write_text(
                'FILE "game.bin" BINARY\n'
                "  TRACK 01 MODE2/2352\n"
                "    INDEX 01 00:00:00\n"
                "  TRACK 02 AUDIO\n"
                "    INDEX 00 00:00:03\n"
                "    INDEX 01 00:00:04\n",
                encoding="utf-8",
            )

            result = analyze_disc(cue)

            self.assertEqual(result.disc_id, "SCES02834")
            self.assertEqual(result.region, "pal")
            self.assertEqual(result.sector_count, 6)
            self.assertEqual(result.sha256, hashlib.sha256(source).hexdigest())
            self.assertEqual(result.sha1, hashlib.sha1(source).hexdigest())
            self.assertEqual([track.mode for track in result.tracks], ["MODE2/2352", "AUDIO"])
            self.assertEqual(result.tracks[0].stop_sector, 2)
            self.assertEqual(result.tracks[1].start_sector, 4)
            self.assertTrue(result.has_audio)
            self.assertEqual(image.read_bytes(), source)

    def test_analyzes_bare_raw_image(self):
        with tempfile.TemporaryDirectory() as directory:
            image = Path(directory) / "disc.bin"
            image.write_bytes(disc_bytes(2, b"SLUS_000.01"))

            result = analyze_disc(image)

            self.assertEqual(result.format, "bin")
            self.assertEqual(result.disc_id, "SLUS00001")
            self.assertEqual(result.region, "ntsc-u")
            self.assertEqual(result.tracks[0].stop_sector, 1)

    def test_analyzes_ccd_track_table(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            image = root / "Game.img"
            image.write_bytes(disc_bytes(3, b"SLPS_000.01"))
            ccd = root / "Game.ccd"
            ccd.write_text(
                "[CloneCD]\nVersion=3\n"
                "[TRACK 1]\nMODE=2\nINDEX 1=0\n",
                encoding="utf-8",
            )

            result = analyze_disc(ccd)

            self.assertEqual(result.format, "ccd")
            self.assertEqual(result.disc_id, "SLPS00001")
            self.assertEqual(result.tracks[0].stop_sector, 2)

    def test_analyzes_zip_cue_without_extracting(self):
        with tempfile.TemporaryDirectory() as directory:
            archive_path = Path(directory) / "disc.zip"
            source = disc_bytes(2, b"SCUS_000.02")
            with zipfile.ZipFile(archive_path, "w") as archive:
                archive.writestr(
                    "set/Game.cue",
                    'FILE "Game.bin" BINARY\n'
                    "  TRACK 01 MODE2/2352\n"
                    "    INDEX 01 00:00:00\n",
                )
                archive.writestr("set/Game.bin", source)

            result = analyze_disc(archive_path)

            self.assertEqual(result.format, "zip/cue")
            self.assertEqual(result.disc_id, "SCUS00002")
            self.assertEqual(result.sha256, hashlib.sha256(source).hexdigest())
            self.assertEqual(list(Path(directory).iterdir()), [archive_path])

    def test_marks_chd_as_incomplete_without_external_metadata(self):
        with tempfile.TemporaryDirectory() as directory:
            chd = Path(directory) / "disc.chd"
            chd.write_bytes(b"MComprHD" + bytes(128))

            result = analyze_disc(chd)

            self.assertFalse(result.complete)
            self.assertIsNone(result.sector_count)
            self.assertIn("chdman", result.warnings[0])

    def test_rejects_unsafe_zip_path(self):
        with tempfile.TemporaryDirectory() as directory:
            archive_path = Path(directory) / "disc.zip"
            with zipfile.ZipFile(archive_path, "w") as archive:
                archive.writestr("../disc.bin", disc_bytes(1))

            with self.assertRaisesRegex(DiscAnalysisError, "unsafe path"):
                analyze_disc(archive_path)

    def test_groups_detected_titles_before_filenames(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            first_path = root / "First.bin"
            second_path = root / "Unrelated.bin"
            first_path.write_bytes(disc_bytes(1, b"SCUS_000.01"))
            second_path.write_bytes(disc_bytes(1, b"SCUS_000.02"))
            first = replace(analyze_disc(first_path), title="Example Game")
            second = replace(analyze_disc(second_path), title="Example Game")

            groups = group_disc_sets((first, second))

            self.assertEqual(len(groups), 1)
            self.assertEqual(len(groups[0].discs), 2)


if __name__ == "__main__":
    unittest.main()
